- package.json
> fix(package) Make sure the ./bin directory is published

- package-lock.json
- packages/markdown-common/package.json
> chore(dep) Upgrade to Concerto 0.80.2

- README.md
<OVERALL SUMMARY OF PULL REQUEST>
- Update this URL https://models.accordproject.org/cicero/dom.html
> fix(README): broken link - I37

- CONTRIBUTING.md
<OVERALL SUMMARY OF PULL REQUEST>
- added CONTRIBUTING doc file.
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
> docs(CONTRIBUTING): init contributor doc - I16

- DEVELOPERS.md
resolves #17
Signed-off-by: Ranadeep Polavarapu <ranadeep   [at]    icloud.com>
<OVERALL SUMMARY OF PULL REQUEST>
- add DEVELOPERS.md
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
> docs(DEVELOPERS): init developer doc - I17

- packages/markdown-cli/README.md
- packages/markdown-cli/package.json
- packages/markdown-common/src/__snapshots__/CommonMarkTransformer.test.js.snap
- packages/markdown-common/test/data/fixed.md
> fix(CLI) yargs was wrongly listed in devDependencies

- package-lock.json
- packages/markdown-cli/test/data/acceptance-slate.json
- packages/markdown-slate/src/SlateTransformer.test.js
- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/test/data/acceptance.json
Needed variables and computed variables to be inlines, not blocks.
> fix(test): variables from blocks to inlines

- package-lock.json
- packages/markdown-cli/test/data/acceptance-slate.json
- packages/markdown-slate/src/SlateTransformer.test.js
- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/src/slateToCiceroMarkDom.js
- packages/markdown-slate/test/data/acceptance.json
Updated variable and computed variable to use nested text nodes.
> Irmerk dselman ciceroui

- README.md
- added license badge
- None
- accordproject/techdocs/issues/82
> docs(README): add license badge

- package-lock.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
> chore(dep) Upgrade to Concerto 0.81.1

- README.md
- added slack badge
- added build badge
- accordproject/techdocs/issues/82
- accordproject/techdocs/issues/78
> docs(README): add slack and build badge

- README.md
Signed-off-by: DEBSUBHRO <debsubhro.roy10@yahoo.com>
* Centering the heading **Markdown-Transform**.
* Centering the corresponding badges below.
- Issue #79 
- Pull Request #43
> doc(README): centering title and badges

- packages/markdown-cli/index.js
> fix(CLI) Uses the new Logger in Concerto

- CONTRIBUTING.md
Signed-off-by: Akshit Sarin <akshitsarin99@gmail.com>
• 'fast-fowarding' to 'fast-forwarding'
• 'seperate' to 'separate'
Changed spellings of 2 words
> Fixed 2 typos in CONTRIBUTING.md

- README.md
> fix(README) Slack badge broken

- README.md
> fix(README) Re-re-fix the Slack badge

- README.md
> fix(README) Re-re-re-fix the Slack badge

- CONTRIBUTING.md
- DEVELOPERS.md
- README.md
Signed-off-by: Michael Zhou <myz227@nyu.edu>
<OVERALL SUMMARY OF PULL REQUEST>
Updated markdown files by correcting for incorrect markdown links, integrating existing links into new markdown, and ensuring consistency in markdown style. Also fixes typos, grammar, and punctuation errors in documentation. All tests confirmed to pass.
- Modified markdown to be more appropriate with content of associated links
- Fixed typos and miscellaneous errors in punctuation and grammar
- [Cicero Template Library Issue 257](https://github.com/accordproject/cicero-template-library/issues/257)
- Pull Request [#280](https://github.com/accordproject/cicero-template-library/pull/280)
> docs(*): update markdown files and fix typos - I18

- .travis/base.sh
- .travis/deploy.sh
- README.md
> chore(deploy) Enable alpha/beta release

- README.md
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
> chore(dep) Upgrade to Concerto 0.82.2

- packages/markdown-cicero/jest.config.js
- packages/markdown-cli/lib/Commands.js
- packages/markdown-cli/test/cli.js
- packages/markdown-cli/test/data/sample.md
- packages/markdown-common/jest.config.js
- packages/markdown-html/jest.config.js
- packages/markdown-slate/jest.config.js
> chore(test) Some more work on test coverage

- packages/markdown-cicero/src/CiceroMarkTransformer.js
- packages/markdown-cicero/src/CiceroMarkTransformer.test.js
- packages/markdown-cicero/src/ToCiceroVisitor.js
- packages/markdown-cicero/src/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-common/src/CommonMarkTransformer.js
- packages/markdown-common/src/CommonMarkTransformer.test.js
- packages/markdown-common/src/__snapshots__/CommonMarkTransformer.test.js.snap
This is adding a test to show that the proposed solution to the issue works. (See jest snapshot for that test)
> test(clause) Test code to access the text content of a Clause node

- README.md
> fix(doc) Update readme

- README.md
> fix(readme) Wrong CLI install

- README.md
> fix(readme) links to CommonMark and CiceroMark CTOs

- README.md
- package-lock.json
- packages/markdown-cicero/package.json
- packages/markdown-cicero/scripts/getExternalModels.js
- packages/markdown-cicero/src/CiceroMarkTransformer.test.js
- packages/markdown-cicero/src/ToCiceroVisitor.js
- packages/markdown-cicero/src/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-cicero/test/data/html-inline-uri.md
- packages/markdown-cicero/test/data/variable.md
- packages/markdown-cli/README.md
- packages/markdown-cli/index.js
- packages/markdown-cli/lib/Commands.js
- packages/markdown-cli/package.json
- packages/markdown-cli/test/cli.js
- packages/markdown-common/package.json
- packages/markdown-common/scripts/getExternalModels.js
- packages/markdown-common/src/CommonMarkTransformer.js
- packages/markdown-common/src/__snapshots__/CommonMarkTransformer.test.js.snap
- packages/markdown-common/test/data/html-inline-uri.md
- packages/markdown-common/test/data/variable.md
- packages/markdown-slate/test/data/variable.md
> refactor(scripts) Simpler external model load script

- README.md
Signed-off-by: Archit garg4.ag@gmail.com
I found some Improper word choice as well as Improper formatting for that I have made changes and corrected that so, now It will be easier for everyone to read.
Please Merge this
> fix(README): grammar

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/README.md
- packages/markdown-cli/index.js
- packages/markdown-cli/lib/Commands.js
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
> fix(cli) Adjusts CLI options and update README

- package-lock.json
- packages/markdown-slate/package.json
Signed-off-by: irmerk <jolenelanglinais@gmail.com>
> chore(package): remove vulnerable unused packages

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
> chore(dep) Upgrade to latest Concerto 0.82.5

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
> chore(dep) Upgrade to Concerto 0.82.6

- packages/markdown-cicero/src/FromCiceroVisitor.js
> fix(cicero) Computed variables should be enclosed in  if not wrapped

- packages/markdown-cicero/src/FromCiceroVisitor.js
- packages/markdown-cicero/src/ToCiceroVisitor.js
- packages/markdown-cicero/src/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-cicero/test/data/clauseulist.md
- packages/markdown-cicero/test/data/ulist.md
- packages/markdown-common/src/CommonMarkTransformer.js
- packages/markdown-common/src/ToMarkdownStringVisitor.js
- Add support for ListVariable, based on code blocks
- Escapes backquotes in code blocks to handle nesting
> New Support for Variables Lists in CiceroMark

- packages/markdown-common/src/ToMarkdownStringVisitor.js
- packages/markdown-common/src/__snapshots__/CommonMarkTransformer.test.js.snap
- packages/markdown-common/test/data/listcodeblock.md
> fix(commonmark) No need for new line after codeblock, handled by blocks

- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/src/slateToCiceroMarkDom.js
- packages/markdown-slate/test/data/ulist.json
- packages/markdown-slate/test/data/ulist.md
> fix(slate) Add variable list roundtrip to Slate transform

- README.md
- architecture.puml
- packages/markdown-cli/README.md
- packages/markdown-cli/index.js
- packages/markdown-html/README.md
> fix(README) Update PUML and READMEs and command line options for HTML

- packages/markdown-html/src/rules.js
> fix(HTML) Lists default to tight unless specified explicitely

- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/slateToCiceroMarkDom.js
Improves emphasis support for generality, and applies to CiceroMark variables.
- More general support for pushing emphasis into marks in Slate transform
- Applies new support to emphasis around inlined CiceroMark variables, fixes #148
- Avoid creating text nodes with `null` use `''` instead
> fix(Slate) Redo emphasis support, including for inlines #148

- packages/markdown-cicero/src/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-cicero/test/data/ulist2.md
- packages/markdown-common/src/CommonMarkTransformer.js
- packages/markdown-common/src/ToMarkdownStringVisitor.js
- packages/markdown-common/src/__snapshots__/CommonMarkTransformer.test.js.snap
- packages/markdown-common/test/data/copyright.tem.md
- packages/markdown-common/test/data/headingdigit3.md
- packages/markdown-common/test/data/miniblockquote.md
- packages/markdown-common/test/data/nestedblockquote2.md
- packages/markdown-common/test/data/ulist3.md
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/test/data/empty.json
Various bug fixes
- Another revision to how nested blocks and new lines are handles, some additional tests (#167)
- More rigorous headings character escaping in text nodes (#168 )
- Add empty paragraph for empty markdown documents (#169 )
> Various bug fixes #167 #168 #169

- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/src/slateToCiceroMarkDom.js
- packages/markdown-slate/test/data/html.json
- packages/markdown-slate/test/data/image-notitle.json
- packages/markdown-slate/test/data/image-notitle.md
- packages/markdown-slate/test/data/link-notitle.json
- packages/markdown-slate/test/data/link-notitle.md
- packages/markdown-slate/test/data/link.md
> test(Slate) Add a few tests, cleanup code

- README.md
> fix(README) correct lerna version

- packages/markdown-slate/README.md
- packages/markdown-slate/src/SlateTransformer.js
- packages/markdown-slate/src/ToSlateVisitor.js
- ...one more PR to fix jsdoc and readme before release.
> chore(doc) Fixes comments and README for new version

- packages/markdown-cicero/src/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-cicero/src/unescapeExpressions.js
> fix(unescape) Bug in object copying

- packages/markdown-transform/lib/transform.js
- packages/markdown-transform/package.json
> chore(build) Clean up package.json in markdown-transform package

- packages/markdown-html/README.md
Signed-off-by: Diana Lease <dianarlease@gmail.com>
- Issue #226
> docs(README): document necessary webpack config

- packages/markdown-cicero/src/CiceroMarkTransformer.js
- packages/markdown-slate/src/ToSlateVisitor.js
> fix(slate) do not add src to clause data if missing

- packages/markdown-template/lib/combinators.js
- Fixes bug parsing the new syntax for formula in contract / clause text
> fix(template) Bug in new syntax parsing for formulas

- packages/markdown-template/lib/parsermanager.js
- packages/markdown-template/test/parsermanager.js
> fix(template) Add setter for template kind to parser manager

- packages/markdown-template/lib/TemplateMarkTransformer.js
- packages/markdown-template/lib/parsermanager.js
- Clean up / adjustment to current time handling in API and parser manager
> fix(template) Adjust current time handling in API

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
> chore(dep) Upgrade to late Concerto 0.82.8

- .travis/deploy.sh
- package-lock.json
- package.json
- packages/dingus/.gitignore
- packages/dingus/lib/index.js
- packages/dingus/lib/index.pug
- packages/dingus/lib/index.styl
- packages/dingus/lib/sample.md
- packages/dingus/package.json
- packages/dingus/scripts/build_demo.js
- packages/dingus/scripts/demodata.js
A dingus based on the markdown-it demo, but focused on templatemark.
> feature(dingus) WIP : initial ciceromark dingus

- packages/dingus/lib/index.js
- packages/dingus/lib/index.pug
- packages/dingus/lib/templatemark.css
> fix(dingus) checks as radios

- README.md
- packages/dingus/lib/index.pug
- packages/dingus/lib/sample.md
- packages/dingus/lib/templatemark.css
- packages/dingus/scripts/demodata.js
> fix(dingus) Some final cleanup, version number and README

- packages/dingus/lib/sample.md
> fix(dingus) Grammar!

- packages/markdown-pdf/src/PdfTransformer.js
- packages/markdown-pdf/src/__snapshots__/PdfTransformer.test.js.snap
> fix(pdf) Do not preserve page breaks by defaults on import

- package-lock.json
- packages/markdown-cicero/index.js
- packages/markdown-cicero/lib/CiceroMarkTransformer.js
- packages/markdown-cicero/lib/Decorators.js
- packages/markdown-cicero/lib/Decorators.test.js
- packages/markdown-cicero/test/data/decorators/boolean.json
- packages/markdown-cicero/test/data/decorators/identifier.json
- packages/markdown-cicero/test/data/decorators/invalid-arg-name.json
- packages/markdown-cicero/test/data/decorators/invalid-odd.json
- packages/markdown-cicero/test/data/decorators/multi.json
- packages/markdown-cicero/test/data/decorators/number.json
- packages/markdown-cicero/test/data/decorators/string.json
- packages/markdown-pdf/src/ToPdfMakeVisitor.js
- packages/markdown-pdf/src/__snapshots__/PdfTransformer.test.js.snap
- packages/markdown-pdf/test/data/signature/grammar.tem.md
- packages/markdown-pdf/test/data/signature/model.cto
- packages/markdown-pdf/test/data/signature/signature-block.md
- Adds a Decorators class to make it easier to work with Decorators
- Adds tests
- Fixes existing tests after model change
> feat (decorators) : add utility and tests for working with decorators

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
- Update to latest version of Concerto `0.82.11`
> chore(dep) Upgrade to Concerto 0.82.11

- packages/markdown-docx/package.json
> fix(package): correct typo

- package.json
Signed-off-by: irmerk <jolenelanglinais@gmail.com>
Follow up on #352
> fix(package): resolve coveralls action

- .github/workflows/build.yml
- package-lock.json
- package.json
Continues #353, `npm audit fix`
> chore(package): init dayjs

- lerna.json
> fix(lerna): resolve allowed publish branch

- .github/workflows/build.yml
- .github/workflows/publish.yml
> fix(github): ignore dingus on npm publish

- packages/dingus/package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-docx/package.json
- packages/markdown-html/package.json
- packages/markdown-it-cicero/package.json
- packages/markdown-it-template/package.json
- packages/markdown-pdf/package.json
- packages/markdown-slate/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
Signed-off-by: Aniruddha Shriwant <aniruddhashriwant@gmail.com>
-  Added Package Repository Information (directory) in `package.json` <ONE>
> feat(package): add repository information to package.json

- .github/workflows/build.yml
- .github/workflows/publish.yml
- package-lock.json
Fixes: https://github.com/accordproject/markdown-transform/issues/364
- Update GitHub workflows to align with the latest in Concerto
> chore(build) Adjust GitHub workflows based on latest in Concerto

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
- Upgrade to latest Concerto `1.0.0-alpha.6`
> chore(dep) Upgrade Concerto to 1.0.0-alpha6

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
- Upgrade to Concerto `1.0.0-alpha.10`
- Should fix recent issues with TemplateMark Dingus
> chore(dep) Upgrade Concerto to 1.0.0-alpha.10

- lerna.json
- package-lock.json
- packages/markdown-cicero/lib/__snapshots__/CommonMarkSpec.test.js.snap
- packages/markdown-common/lib/__snapshots__/CommonMarkSpec.test.js.snap
- packages/markdown-common/package.json
- Upgrade to `xmldom@0.5.0` including bug and vulnerability fixes
> chore(dep) Upgrade to xmldom 0.5

- package-lock.json
- packages/markdown-html/package.json
- Upgrade to jsdom `16.7`
- Tests sill pass, seems to work fine
> chore(dep) Upgrade jsdom to 16.7 in the HTML transform

- packages/markdown-cli/index.js
- packages/markdown-cli/lib/commands.js
- packages/markdown-cli/package.json
- packages/markdown-cli/test/cli.js
- packages/markdown-cli/test/data/promissory-note.md
- packages/markdown-cli/test/extension/toc.js
- packages/markdown-cli/test/extension/wordcount.js
- packages/markdown-transform/lib/transformEngine.js
- packages/markdown-transform/test/transformEngine.js
- Add `--extension` option to the CLI for user-defined extensions to the transforms
- Cleaner extension API
- Some more testing, including a mini table of content transform
> feature(transform) CLI/consolidation/cleanup/testing of transform extensions

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
- Upgrade to the latest published Concerto `1.2.1`
> chore(dep) Upgrade to Concerto 1.2.1

- package-lock.json
- Fixes to `package-lock.json`
> chore(build) fixes to package-lock.json

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
- Upgrade to Concerto `2.0.0-alpha.2`
> feature(dep): Switch to Concerto 2.0.0-alpha.2

- package-lock.json
- packages/markdown-docx/package.json
- packages/markdown-docx/webpack.config.js
- packages/markdown-html/package.json
- packages/markdown-html/webpack.config.js
- packages/markdown-pdf/package.json
- packages/markdown-pdf/webpack.config.js
Update web pack configurations for webpack5:
- Different parameters for ignore plugin
- Polyfills for node.js are no longer added automatically and have to be done by hand
> fix(build): Update configuration for webpack 5

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-docx/package.json
- packages/markdown-html/package.json
- packages/markdown-it-cicero/package.json
- packages/markdown-it-template/package.json
- packages/markdown-pdf/package.json
- packages/markdown-slate/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/package.json
- Update all `engines` descriptions in package.json files to require node 14
> chore(build): Update engines constraints in all package.json

- packages/markdown-docx/package.json
- packages/markdown-html/package.json
- packages/markdown-pdf/package.json
- Fixes the browser entry point in package.json
- 
- <ONE>
- <TWO>
> fix(browser) : correct browser entry point

- .github/workflows/build-and-deploy-dingus.yml
- .github/workflows/build.yml
- .github/workflows/publish.yml
- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-common/package.json
- packages/markdown-template/lib/templatemarkutil.js
- packages/markdown-template/package.json
- packages/markdown-template/src/templatemarkutil.js
- packages/markdown-transform/package.json
- Bumps Concerto version to 3.7.0
- Do not swallow exceptions when type checking template mark 
- <ONE>
- <TWO>
> chore(concerto) : bump concerto version and throw exceptions
