- bin/index.js
- package-lock.json
- package.json
- src/Commands.js
- src/Commonmark.test.js
- src/CommonmarkAP.test.js
- src/CommonmarkFromAP.js
- src/CommonmarkParser.js
- src/CommonmarkToAP.js
- src/FromAPVisitor.js
- src/Models.js
- src/ToAPVisitor.js
- src/ToStringVisitor.js
- src/__snapshots__/Commonmark.test.js.snap
- src/__snapshots__/CommonmarkAP.test.js.snap
- Add new AST nodes `Clause` `Variable` `ComputedVariable`
- Add conversion from vanilla CommonMark AST to AST with new nodes
- Some testing that it does not break parsing and serialisation
> Feature: Add new nodes and transforms for Accord Project tags in CommonMark 

- index.js
- src/Commands.js
- src/CommonmarkAP.test.js
- src/CommonmarkFromAP.js
- src/CommonmarkParser.js
- src/CommonmarkToAP.js
- src/FromAPVisitor.js
- src/Models.js
- src/ToAPVisitor.js
- src/__snapshots__/Commonmark.test.js.snap
- src/__snapshots__/CommonmarkAP.test.js.snap
- test/clause.md
- Separate Cicero extension to markdown in its own model
- Small adjustments to type hierarchy for `Variable` `ComputedVariable` and `Clause`
- Expose Cicero support in `index.js`
> Refactor: Cleaning up models and Index

- bin/index.js
- src/CiceroMark.js
- src/Commands.js
- src/CommonMark.js
- src/FromCiceroVisitor.js
- src/Models.js
- src/ToCiceroVisitor.js
- src/ToStringVisitor.js
- src/__snapshots__/CiceroMark.test.js.snap
- src/__snapshots__/CommonMark.test.js.snap
- test/clause.md
- Clauses are now recognised through the info part of the code block
- Bug fixes to clauses containing variables
- Add convenience calculation for clause text without variables tags
> Clause Nodes fixes

- packages/markdown-cli/index.js
- packages/markdown-cli/lib/Commands.js
- packages/markdown-common/src/CommonMark.js
- packages/markdown-common/src/ToMarkdownStringVisitor.js
This is useful when using markdown transform to for Cicero parsing.
> feature(list) add option to not index lists when generating markdown

- README.md
- package.json
- packages/markdown-cli/README.md
- packages/markdown-cli/package.json
- packages/markdown-cli/test/data/acceptance.json
- packages/markdown-common/src/CommonMarkTransformer.js
- Names CLI `markus`
- Validates when converting from markdown to CommonMarkDOM even when format is `json`
- Small fixes to README and build commands
> Small fixes for release 0.4.0

- README.md
- architecture.puml
- package-lock.json
- packages/markdown-cli/index.js
- packages/markdown-cli/lib/Commands.js
- packages/markdown-cli/package.json
- packages/markdown-common/src/ToMarkdownStringVisitor.js
- packages/markdown-common/src/__snapshots__/CommonMarkTransformer.test.js.snap
- packages/markdown-common/test/data/editor.md
- Fixes transition to headings missing new lines
- Adds HTML to command line
- Add missing `yargs` dependency to `markdown-cli`
- Fixes help message with `markus` name
- Update architecture diagram
> Various fixes to CLI and new lines in transforms

- packages/markdown-cli/test/data/acceptance-slate.json
- packages/markdown-slate/src/SlateTransformer.test.js
- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/test/data/acceptance.json
Moving the `text` value from `data` to `nodes`
- Unable to resolve these two failing tests:
- https://github.com/accordproject/markdown-transform/blob/3878ac6253a92f9c50713c9ba8cbe42b04273f7a/packages/markdown-cli/test/cli.js#L87
- https://github.com/accordproject/markdown-transform/blob/3878ac6253a92f9c50713c9ba8cbe42b04273f7a/packages/markdown-cli/test/cli.js#L55
- Resolved some failing tests (`packages/markdown-slate/src/SlateTransformer.test.js`) by adding `'marks': [],`, which doesn't seem like it was necessary. This lead to the remaining failing tests, which a text diff checker finds that the error is the included `'marks': [],`
> fix(slate): move text value from data to nodes

- packages/markdown-common/src/ToMarkdownStringVisitor.js
Cleanup of normalisation for thematic break (remove unnecessary new line).
> fix(common) Remove extra newline when printing thematic breaks

- packages/markdown-html/src/ToHtmlStringVisitor.js
- packages/markdown-html/src/__snapshots__/HtmlTransformer.test.js.snap
Uses `<span>` elements instead of `<div>` for `Variable` and `ComputedVariable` as they are inline elements which should not be rendered with line breaks by default
Before:
After:
> feat(ToHtmlStringVisitor): Switch variable elements to span tags

- packages/markdown-html/src/ToHtmlStringVisitor.js
- packages/markdown-html/src/__snapshots__/HtmlTransformer.test.js.snap
Replaces the invalid `emph` tag with `em` in the HTML string visitor
> fix(ToHtmlStringVisitor): Replace emph with em tag

- package-lock.json
- packages/markdown-slate/README.md
- packages/markdown-slate/package.json
Signed-off-by: Diana Lease <dianarlease@gmail.com>
- removes slate from dependencies
- adds slate as a peer dependency
- also adds slate as a dev dependency since it is needed for the tests
> chore(deps): move slate to peerDep and devDep for tests

- packages/markdown-common/src/ToMarkdownStringVisitor.js
- packages/markdown-common/src/__snapshots__/CommonMarkTransformer.test.js.snap
- packages/markdown-common/test/data/nested-list.md
- Remove extraneous new line at the beginning of lists which breaks the tight/not tight distinction in nested lists.
- Add corresponding nested list test
> fix(list) Does not add extraneous new lines in list (#110)

- package-lock.json
- packages/markdown-cli/test/cli.js
- packages/markdown-cli/test/data/acceptance-slate.json
- packages/markdown-slate/src/SlateTransformer.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/src/slateToCiceroMarkDom.js
- packages/markdown-slate/test/data/acceptance.json
- packages/markdown-slate/test/data/latedelivery.json
- Create an empty Slate DOM paragraph block and to tack onto any transform from CiceroMark
- Still will require Slate work to handle runtime editing and adding a template to the end of a contract
- N/A
> feat(markdown-slate): push empty paragraph onto slate dom

- packages/markdown-slate/src/slateToCiceroMarkDom.js
Fixes an issue with disappearing nods when one node contains a first node with empty text but more nodes after.
> fix(slate) only remove nodes with a single empty text node

- packages/markdown-html/src/ToHtmlStringVisitor.js
- packages/markdown-html/src/__snapshots__/HtmlTransformer.test.js.snap
- packages/markdown-html/src/rules.js
Signed-off-by: Diana Lease <dianarlease@gmail.com>
- Currently, the transform uses `wbr` for softbreaks, which is not semantically correct and causes issues when rendering html in the browser
- Uses `\n` for softbreaks instead of `wbr` when converting to html
- When converting from html, we find each `\n` inside of a text node and insert a softbreak node in its place
- All of the tests currently pass. However, this could use more testing to make sure extraneous softbreaks do not get added where they shouldn't since we use `\n` in other parts of the transform as well.
Related to https://github.com/accordproject/cicero-template-library/pull/313
> fix(markdown-html): updates softbreaks

- packages/markdown-common/src/ToMarkdownStringVisitor.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/src/slateToCiceroMarkDom.js
Addresses low level error when converting code blocks from Slate to Markdown.
- More defensive access to node text in `markdown-transform`
- Proper creation of text field in CodeBlock when translating from slate.
- Would be nice if the constraints that leaf nodes (Text, CodeBlock, etc) must have a text content and must node have children nodes was enforced by the CTO model.
> fix(codeblock) Properly create text from Slate code block to CiceroMark

- packages/markdown-common/src/ToMarkdownStringVisitor.js
- More defensive when passing parameters in for paragraphs (since it now passes parameters).
> refactor(common) Safely copy parameters for paragraphs

- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/src/slateToCiceroMarkDom.js
- packages/markdown-slate/test/data/html.md
- Bug fixes so that HTML Blocks roundtrip in Slate transform
- Add appropriate support for HTML Inlines in Slate transform
> fix(Slate) HTML Blocks and Inlines now should roundtrip

- packages/markdown-cli/package.json
- packages/markdown-cli/test/data/acceptance-slate.json
- packages/markdown-slate/package.json
- packages/markdown-slate/src/SlateTransformer.js
- packages/markdown-slate/src/SlateTransformer.test.js
- packages/markdown-slate/src/ToSlateVisitor.js
- packages/markdown-slate/src/slateToCiceroMarkDom.js
- packages/markdown-slate/test/data/quote.json
Disantangle markdown slate transformation from slate dependency, focusing on JSON representation.
- This is a _non backward compatible change_ the code using the `markdown-slate` transform is now responsible for calling `Value.toJSON` and `Value.fromJSON` to get the Slate DOM.
- Suggested as part of Issue #175
> refactor(slate) Remove slate dependency, relying on Slate JSON instead

- packages/markdown-slate/package.json
- Remove unused peer dependencies on slate in the `markdown-slate` transform
> fix(slate) Remove now unnecessary peer dependencies on slate

- packages/markdown-html/src/ToHtmlStringVisitor.js
- packages/markdown-html/src/__snapshots__/HtmlTransformer.test.js.snap
- packages/markdown-html/src/rules.js
- packages/markdown-html/test/data/latedelivery-noforce.md
- packages/markdown-html/test/data/latedelivery.md
- Add translation / rules for handling conditional variables in HTML transform
- Rule to create HTML inline for conditional variables in CiceroMark -> HTML
- Rule to roundtrip back from HTML to CiceroMark
- Tests on late delivery and penalty clauses
- This seems to trip possibly an unrelated bug about softbreaks. I'm leaving this as a draft PR until I can figure it out.
> fix(HTML) Add support for conditional variables in HTML transform (#189)

- packages/markdown-cli/index.js
- packages/markdown-cli/lib/commands.js
Add a `--plainText` option to the `draft` and `normalize` commands in the CLI.
Example run:
```
bash-3.2$ cat test/data/nestedblockquote.md 
Once upon a time
> This is a\
> linebreak.
> This is a quote.
>
> Heading Two
> ----
> This is more text.
> Ordered lists:
> 1. one
>    this has more in it
>    - nested list
>    - etc.
> 2. two
> 3. three
>
> This should be a line
>
> ----
> This should be more text
> > This should be a nested blockquote
> with more things in it
> >
> > And a second paragraph in the nested blockquote
>
> The end of the blockquote
bash-3.2$ ../markdown-cli/index.js normalize --sample test/data/nestedblockquote.md  --plainText --cicero
9:26:36 PM - info: 
Once upon a time
This is alinebreak.This is a quote.
Heading …
```
> feature(CLI) Add --plainText option to CLI

- package-lock.json
- packages/markdown-cicero/src/CiceroMarkTransformer.js
- packages/markdown-cicero/src/CiceroMarkTransformer.test.js
- packages/markdown-cicero/src/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-cicero/src/unescapeExpressions.js
Adds a option `unescapeExpressions` to the CiceroMark `toCommonMark` transform that converts `Variable` and `ComputedVariable` node in the AST to `Text` nodes. This is helpful when you want to render a template instance with out variable syntax e.g. `"Party A"` and `{{"10.2%"}}` becomes `Party A` and `10.2%` respectively
> feat(ciceromark): Adds option to remove expressions from CiceroMark

- packages/markdown-cicero/src/CiceroMarkTransformer.js
- packages/markdown-cicero/src/CiceroMarkTransformer.test.js
- packages/markdown-cicero/src/UnquoteVariables.js
- packages/markdown-cicero/src/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-cli/index.js
- packages/markdown-cli/lib/commands.js
- Name change: from `unescapeExpressions` to `unquoteVariables`, using the same model as `unwrapVariables
- Allow unescape expressions both on the to cicero and from cicero route (for e.g., HTML)
- Some more testing
- Adds `--unquoteVariables` as an option to the CLI
- A bit of CLI simplification
> Reactor / Expand unquoting for variables

- packages/markdown-cicero/lib/CiceroEditTransformer.test.js
- packages/markdown-cicero/lib/CiceroMarkTransformer.js
- packages/markdown-cicero/lib/CiceroMarkTransformer.test.js
- packages/markdown-cicero/lib/FromCiceroEditVisitor.js
- packages/markdown-cicero/lib/__snapshots__/CiceroEditTransformer.test.js.snap
- packages/markdown-cicero/lib/__snapshots__/CiceroMarkTransformer.test.js.snap
- packages/markdown-cicero/test/data/ciceroedit/acceptance-notclause2.md
- packages/markdown-cicero/test/data/ciceroedit/acceptance-notformula.md
- packages/markdown-cicero/test/data/ciceroedit/latedelivery-else.md
- packages/markdown-cicero/test/data/ciceroedit/latedelivery-notif.md
- packages/markdown-cicero/test/data/ciceroedit/latedelivery-onlyelse.md
- packages/markdown-cicero/test/data/ciceromark/acceptance-nosrc.md
- packages/markdown-cicero/test/data/ciceromark/acceptance-notclause2.md
- packages/markdown-cicero/test/data/ciceromark/acceptance-notformula.md
- packages/markdown-cicero/test/data/ciceromark/latedelivery-else.md
- packages/markdown-cicero/test/data/ciceromark/latedelivery-notif.md
- packages/markdown-cicero/test/data/ciceromark/latedelivery-onlyelse.md
- Remove now unnecessary codeblock text processing function
- Improves code coverage, notably for ciceroedit transform
- rename `quoteVariables` option to `unquoteVariables`, more consistent with `removeFormatting`
- clean up implementation of `unquoteVariables`
> chore(cicero) More testing, adjust API, remove unused code

- packages/markdown-it-cicero/lib/index.js
- packages/markdown-it-cicero/test/data/all.html
- packages/markdown-it-template/lib/index.js
- packages/markdown-it-template/test/data/all.html
- packages/markdown-it-template/test/data/autoclose1.html
- packages/markdown-it-template/test/data/autoclose2.html
- packages/markdown-it-template/test/data/autoclose3.html
- packages/markdown-it-template/test/data/clause1.html
- packages/markdown-it-template/test/data/clause2.html
- packages/markdown-it-template/test/data/clause3.html
- packages/markdown-it-template/test/data/clause4.html
- packages/markdown-it-template/test/data/clause5.html
- packages/markdown-it-template/test/data/clause6.html
- packages/markdown-it-template/test/data/none.html
- packages/markdown-it-template/test/data/notclause1.html
- packages/markdown-it-template/test/data/notclause2.html
- packages/markdown-it-template/test/data/notclause3.html
- packages/markdown-slate/lib/SlateTransformer.js
- packages/markdown-slate/lib/SlateTransformer.test.js
- packages/markdown-slate/lib/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/test/data/ciceromark/acceptance.md
- Better native render for markdown-it plugins.
- new `SlateTransformer.toMarkdownCicero` call for convenience
> Post 0.12 release fixes: HTML rendering and toMarkdownCicero for Slate transform

- packages/markdown-it-template/lib/index.js
- packages/markdown-it-template/test/data/all.html
- packages/markdown-template/lib/parsermanager.js
- packages/markdown-template/test/parsermanager.js
-  #277 More robust API for building and rebuilding the parser
- New special variable `{{this}}` rendered as `<span class="variable" name="this">this</span>`
- This change is actually making sense, since the parsing table serves both as the external description (i.e., declarative mapping from types to parsers) and internally is annotated by (possibly recursive) javascript functions when building the parser.
> Critical bug fix for parser rebuilding + handling of {{this}} in templatemark plugin rendering

- packages/markdown-template/lib/TemplateMarkTransformer.js
- packages/markdown-template/lib/TypeVisitor.js
- packages/markdown-template/lib/errorutil.js
- packages/markdown-template/test/TemplateMarkTransformer.js
- Traps low-level error for inconsistent variable in parser to return them as `ParseException`
- Also passes ast node to template exception (unused for the time being, but consistent with the API)
> fix(template) Proper parse exception for inconsistant variables

- package-lock.json
- packages/markdown-pdf/src/ToPdfMakeVisitor.js
- packages/markdown-pdf/test/data/contract2.md
- Protect the PDF transform from CiceroMark document that contain headings without text
> fix(markdown-pdf): crash with empty headings

- packages/dingus/lib/index.js
Enables parsing for HTML blocks&inlines in the dingus with the `templatemark` and `ciceromark` option.
> fix(dingus) Should parse with HTML option on

- package-lock.json
- packages/markdown-pdf/test/data/contract.md
Update the test contract for the markdown-pdf transform to use the Cicero v0.21 syntax for embedded clauses.
> test(markdown-pdf) : update test contract with embedded clause

- packages/markdown-pdf/src/ToPdfMakeVisitor.js
Fixes various issues with pdf generation.
- Switch from `text` to `stack` in pdfmake JSON for complex blocks
- Fixes various issues with lists, blockquotes and clauses text in the generated pdf
- I have low confidence -- not sure if it breaks other things, my first time looking at pdfmake.
For:
```
This is the introduction.
> 
> This is a quote.
> 
> This is more text.
>
This is the conclusion.
This is a list
- Foo
Bar
```
Before: 
[test0.pdf](https://github.com/accordproject/markdown-transform/files/5143202/test0.pdf)
After:
[test.pdf](https://github.com/accordproject/markdown-transform/files/5143203/test.pdf)
For: [contract-5f4513931f0dca001b5aff0c-2020-08-25T13_37_44.813Z.md.zip](https://github.com/accordproject/markdown-transform/files …
> fix(pdfmake) Use stack property instead of text for nested blocks

- package-lock.json
- package.json
- packages/markdown-cicero/package.json
- packages/markdown-cli/index.js
- packages/markdown-cli/package.json
- packages/markdown-common/package.json
- packages/markdown-template/package.json
- packages/markdown-transform/lib/transform.js
- packages/markdown-transform/package.json
- packages/markdown-transform/test/data/template1/contract.cto
- packages/markdown-transform/test/data/template1/money.cto
- packages/markdown-transform/test/transform.js
#321 
- Update to Concerto `0.82.9`
- Allows to pass `--offline` to transform, based on new Concerto API. This allows to run markdown transform on templates (which need a model) without an internet connection.
- Avoid loading models multiple times (unecessarily) in the transform
- Add test for pdf generation for coverage
> feature(cli) Allow to pass --offline option to the transform/CLI

- package-lock.json
- packages/markdown-html/src/__snapshots__/HtmlTransformer.test.js.snap
- packages/markdown-html/src/rules.js
- packages/markdown-html/test/data/markdown/linebreak.md
Issue: #326 
`markdown-html` does not map `Linebreak` in CommonMark to/from `<br/>` in HTML.
- Adds a new rule and snapshot test for markdown linebreak
> fix(markdown-html) : handle linebreaks

- scripts/external/models.json
- Switch back links to models to the officially published versions
> fix(models) switch temporary model links to published ones

- packages/markdown-pdf/src/PdfTransformer.js
- packages/markdown-pdf/test/data/contract.md
Added logic to PDF Transformer to retrieve remote images in TemplateMark as an image reference. 
For example:
`![Accord Logo](https://avatars0.githubusercontent.com/u/29445438?s=200&v=4)`
Logic added to PDF Transformer to walk the document definition and find all `image` objects, and replace the URL strings with image data.
- findReplaceImageUrls
- Walk a JSON object and find any image key starting with 'http' and substitute the URL with the image data.
- findReplaceImageUrls is a recursive function.
- getRemoteImageData
- Asynchronously retrieve image buffer data from URL.
- if an error occurs, getRemoteImageData substitutes a base64 encoded placeholder image.
- added `![Accord](https://avatars0.githubusercontent.com/u/29445438?s=200&v=4)` to test data.
- Added support for offline mode …
> Added support for HTTP URL images in PDF Transform

- packages/markdown-cli/README.md
Signed-off-by: d-e-v-esh <59534570+d-e-v-esh@users.noreply.github.com>
The documentation of the `markdown-cli` is outdated and contains commands that do not work. This PR updates that. The new documentation is copied from [this](https://docs.accordproject.org/docs/ref-markus-cli.html) page where the updated documentation is provided and converted to markdown. 
This issue was highlighted [here](https://github.com/accordproject/web-components/issues/175#issuecomment-801330604).
> docs(README): outdated MD-CLI documentation - #363

- packages/markdown-template/lib/plugins/Double/parse.js
- packages/markdown-template/lib/plugins/Integer/parse.js
- packages/markdown-template/lib/plugins/Long/parse.js
Fixes parser for amount, so they return a number rather than an array with a number in it.
- Add a Parsimmon's `map` to extract the content of the amount.
> fix(template) Properly extract number when parsing amounts

- .github/workflows/build.yml
- GitHub workflow should use `npm ci` rather than `lerna bootstrap` or it won't get external models
- Fix similar to the one in https://github.com/accordproject/ergo/pull/806
> fix(CI) Should use npm install before publish to get external models

- packages/markdown-docx/src/CiceroMarkToOOXMLTransformer.js
Sets up the basic class definition for the CiceroMark to OOXML transformer
- <ONE> Defines constructor
- <TWO> Defines the function for converting CiceroMark to OOXML
- [] Merging to `master` from `fork:branchname`
> feat: sets-up class for CiceroMark to OOXML transformer

- packages/markdown-docx/test/CiceroMarkToOOXMLRoundTrip.test.js
- packages/markdown-docx/test/helper.js
Refactors the test logic in `CiceroMarkToOOXMLRoundTrip.test.js`
- <ONE> Use a function to check for the equality of ciceroMark(s).
- <TWO> Replace the logic with the function.
> refactor: roundtrip test logic - #407

- packages/markdown-docx/.eslintrc.yml
Changes the ecmaVersion to allow eslint to parse spread operator.
- <ONE> Change `ecmaVersion` to `2018`
> chore(markdown-docx): update eslint ecmaVersion

- packages/markdown-docx/src/CiceroMarkToOOXML/index.js
Return counter for variables in CiceroMark
Enhancement to the `CiceroMarkToOOXMLTransformer` by returning the counter for variables in CiceroMark of a template.
- <ONE> Use a class variable `counter` to store the counter.
- <TWO> A function `getCounter()` that returns the counter.
- Pull Request #410
Raised as a part of the above PR.
> feat(markdown-docx): add API to return frequency of variables in CiceroMark (JSON) - #397

- packages/markdown-docx/src/CiceroMarkToOOXML/index.js
Removes the `ooxml` argument in `toOOXML` function and update the docstrings accordingly.
- <ONE> Removes `ooxml` argument.
- <TWO> Docstring update.
- Pull Request #411 <NUMBER>
Raised as a part of discussion in above PR.
> refactor(markdown-docx): remove argument ooxml in `toOOXML` - #397

- package-lock.json
- packages/markdown-pdf/package.json
- packages/markdown-pdf/src/ToCiceroMark.js
- Switch `pdfjs` import for latest distribution `es5` renamed to `legacy`
- See also comment in https://stackoverflow.com/questions/64189359/reading-pdf-from-url-with-node-js-using-pdf-js
> fix(pdf) Switch pdfjs import for latest distribution

- packages/markdown-template/test/TemplateMarkTransformer.js
Pass offline:true in loadModelManager
Signed-off-by: K-Kumar-01 <kushalkumargupta4@gmail.com>
- <ONE> Pass `offline:true` in options in loadModelManager
> fix(markdown-template): Build failure - #422

- packages/markdown-docx/src/ToCiceroMarkVisitor.js
- packages/markdown-docx/src/ToOOXMLVisitor/index.js
- packages/markdown-docx/src/constants.js
Signed-off-by: K-Kumar-01 <kushalkumargupta4@gmail.com>
Created in relation to the [comment](https://github.com/accordproject/markdown-transform/pull/426#discussion_r665536884).
- <ONE> Declare `DEFINED_NODES` in a separate file and export.
- <TWO> Use `DEFINED_NODES` in place of class and nodeType.
> refactor(markdown-docx): use DEFINE_NODES for nodeType and class

- packages/markdown-docx/src/ToOOXMLVisitor/index.js
- packages/markdown-docx/test/helper.js
Removes the return of `counter` variable when converting to `OOXML`.
Raised as a part of the discussion [here](https://github.com/accordproject/markdown-transform/pull/424#discussion_r673341224)
- <ONE> Return only `ooxml` as string in `toOOXML` of the `ToOOXMLVisitor.js`
> refactor(markdown-docx): remove return variable frequency api

- packages/markdown-pdf/src/commonmarkrules.js
- Fixes nested text nodes in pdfmake transform, not handling styles like bold/italics
> fix(pdf) pdfmake transform for bold/italics styles

- packages/markdown-pdf/index.dist.js
- packages/markdown-pdf/src/PdfTransformer.js
- packages/markdown-pdf/src/PdfTransformerBase.js
- packages/markdown-pdf/src/PdfTransformerBrowser.js
This provides better support for pdf transforms in the browser with a browser-enabled version of the `PdfTransformer` class.
- Provides a separate PdfTransformer with browser support which can be used jointly with the `@accordproject/markdown-transform` package
> feature(pdf) Add browser version of PdfTransformer

- packages/markdown-cli/index.js
- Allow loading transform extensions in the CLI that have been built with ES6 "export default"
This means the CLI extension option will allow both:
```javascript
module.exports = {
format: ...
transforms: ...
};
```
and
```javascript
export default {
format: ...
transforms: ...
};
```
> fix(CLI) Allow extensions with ES6 modules exports

- packages/markdown-cli/index.js
- packages/markdown-cli/lib/commands.js
- Do not print out the result if `--output` is used
> fix(CLI) Do not print result if using --output option

- .github/workflows/build-and-deploy-dingus.yml
Creates an GitHub "Action" to build and deploy Templatemark Dingus to AWS S3.
Requires the following "SECRETS" to be specified in GitHub.
```
AWS_ACCESS_KEY_ID: ****
AWS_SECRET_ACCESS_KEY: *****
AWS_REGION : us-east-1
```
Will need to add the following secrets to the repo.
```
AWS_CLOUDFRONT_DISTRIBUTION_ID : E4NC0BLM2QQHM
AWS_S3_BUCKET:  templatemark-dingus.accordproject.org
```
The invalidation is created after each deployment to S3 and can be seen here:
https://console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/distributions/E4NC0BLM2QQHM/invalidations
The S3 Bucket URL for testing is:
http://templatemark-dingus.accordproject.org.s3-website-us-east-1.amazonaws.com/
The CloudFront Distro URL for testing is:
https://defpqedhlibco.cloudfront.net/
> chore(github) - add action to deploy Templatemark Dingus to AWS S3

- packages/markdown-pdf/src/PdfTransformerBase.js
Signed-off-by: Shivam upadhyay <shivam.upadhyay@codinova.com>
- <ONE> Change pdfMakeToPdfStreamWithCallback to include default style only if provided input does not contains defaultStyle
> fix(markdown-pdf) - Allow default styles to be overridden.

- packages/markdown-common/lib/CommonMarkUtils.js
- packages/markdown-common/lib/__snapshots__/CommonMarkTransformer.test.js.snap
- packages/markdown-common/lib/fromcommonmarkrules.js
- packages/markdown-common/lib/tocommonmarkrules.js
- packages/markdown-common/test/data/table.md
- packages/markdown-common/test/data/table_bold.md
- packages/markdown-common/test/data/table_code.md
- packages/markdown-common/test/data/table_image.md
- packages/markdown-common/test/data/table_links.md
- packages/markdown-common/test/data/table_skewed.md
- packages/markdown-html/src/ToHtmlStringVisitor.js
- packages/markdown-html/src/__snapshots__/HtmlTransformer.test.js.snap
- packages/markdown-html/src/rules.js
- packages/markdown-html/test/data/markdown/table.md
- packages/markdown-html/test/data/markdown/table_complex.md
- packages/markdown-pdf/src/commonmarkrules.js
- packages/markdown-pdf/src/pdfmakeutil.js
- packages/markdown-pdf/test/data/tables.md
- packages/markdown-slate/lib/__snapshots__/SlateTransformer.test.js.snap
- packages/markdown-slate/lib/commonmarkfromslaterules.js
- packages/markdown-slate/lib/commonmarktoslaterules.js
- packages/markdown-slate/test/data/markdown/table.json
- packages/markdown-slate/test/data/markdown/table.md
- packages/markdown-slate/test/data/markdown/table_complex.json
- packages/markdown-slate/test/data/markdown/table_complex.md
- scripts/external/models.json
Signed-off-by: TC5022 <tanyac5022002@gmail.com>
- <ONE> This is a WIP PR to add table extension in various packages of markdown-transform
- <TWO>  Currently the changes reflect transformations in common mark DOM, HTML, the slate DOM and PDF
- <ONE> First we will have to merge the new [table models for commonmark and ciceromark](https://github.com/accordproject/models/pull/159) for these changes to be successful.
- <TWO>
> feat(markdown-transform): add table transforms

- package-lock.json
- packages/markdown-template/lib/fromtemplatemarkrules.js
- packages/markdown-template/lib/templaterules.js
- packages/markdown-template/src/fromtemplatemarkrules.js
- packages/markdown-template/src/templaterules.js
- scripts/external/models.json
Updates the project to consume/export TemplateMark version 0.5.0.
- Uses TemplateMark version 0.5.0
- Adds [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat) options on the JoinDefinition node
- <ONE>
- <TWO>
> feat(template) : add Intl.ListFormat options to Join node

- README.md
This repository was listed among the repos that need an update of Slack references to Discord.
- Update Slack references to Discord
- Issue # https://github.com/accordproject/techdocs/issues/388
> fix: update Slack references to Discord

- packages/markdown-template/src/ModelVisitor.js
Removes the require and usage of the util.inspect method.
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> fix: remove require of util package

- package-lock.json
- package.json
- packages/markdown-cicero/jest.config.js
- packages/markdown-cicero/package.json
- packages/markdown-cli/package.json
- packages/markdown-common/jest.config.js
- packages/markdown-common/package.json
- packages/markdown-docx/jest.config.js
- packages/markdown-html/jest.config.js
- packages/markdown-pdf/jest.config.js
- packages/markdown-slate/jest.config.js
- packages/markdown-template/lib/ModelVisitor.js
- packages/markdown-template/lib/errorutil.js
- packages/markdown-template/lib/templatemarkutil.js
- packages/markdown-template/lib/templaterules.js
- packages/markdown-template/package.json
- packages/markdown-transform/jest.config.js
- packages/markdown-transform/package.json
Updates concerto dependencies to the latest versions
- Mapped axios dependency to jest compatible transpiled file where jest is used for testing
> chore(deps): update concerto dependencies
